app/courses/__init__.py
from flask import Blueprint

bp = Blueprint('courses', __name__)

from . import routes

app/courses/routes.py
from . import bp as courses_bp
from flask import render_template, request, session, jsonify, url_for, abort
from flask_login import login_required, current_user
from .services import *


@courses_bp.route('/', methods=['GET', 'POST'])
@login_required
def index():
    icons = {
        'Технический': url_for('static', filename='img/courses/lessons/icons/tech.svg'),
        'Гуманитарный': url_for('static', filename='img/courses/lessons/icons/marketing.svg'),
        'Программирование и т.п': url_for('static', filename='img/courses/lessons/icons/marketing.svg')
    }
    if request.method == "POST":
        return ''
    else:
        course_id = request.args.get('id')
        if course_id:
            course = get_courses_by_id(course_id)
            if course is None:
                return abort(404)
            return render_template(template_name_or_list='courses/course_page.html', course=course, icons=icons)
        else:
            courses = get_courses_able_to_join(current_user.id)
            return render_template(template_name_or_list='courses/courses.html', courses = courses, icons=icons)


@courses_bp.route('/active', methods=['GET', 'POST'])
@login_required
def user_courses():
    icons = {
        'Технический': url_for('static', filename='img/courses/lessons/icons/tech.svg'),
        'Гуманитарный': url_for('static', filename='img/courses/lessons/icons/marketing.svg'),
        'Программирование и т.п': url_for('static', filename='img/courses/lessons/icons/marketing.svg')
    }
    if request.method == "POST":
        return ''
    else:
        courses = get_user_courses(current_user.id)
        return render_template(template_name_or_list='courses/active_courses.html', courses=courses, icons=icons)


@courses_bp.route('/add_to_course', methods=['GET', 'POST'])
@login_required
def add_to_course():
    course_id = request.form.get('course_id')
    status = join_to_course(current_user.id, course_id)
    if status:
        data = {'status': 'success'}
        return jsonify(data)
    else:
        data = {'status': 'error'}
        return jsonify(data)

app/templates/courses/active_courses.html
{% extends 'courses/base.html' %}
{% set active_page = "active_courses" %}
{% block title %}
Курсы
{% endblock %}
{% block styles %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/courses/lessons.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/courses/footer.css') }}">
{% endblock %}
{% block content %}
       <div class="header-text row">
            <div class="column">
                <h1 class="title">СПИСОК ПРЕДМЕТОВ</h1>
                <div class="descryption">
                    Здравствуй, <span class = "active-link">{{ current_user.fullname }}</span>! На этой странице ты
                    можешь просмотреть информацию по интересующим тебя
                    предметам. Она должна помочь в подготовке к экзамену, контрольной или просто штудировании!
                </div>
            </div>
        </div>
    </header>
    <div class="main row">
        <div class="main-wrap column">
            <ul class="tabs row">
                <li class="tab left-tab active-tab">
                    <a href="{{ url_for('courses.user_courses') }}">
                        <div class="row tab-wrap">
                            <img src="{{ url_for('static', filename='img/courses/lessons/icons/check-list.svg') }}" alt=""> <span class="tab-title">Выбранные
                                предметы</span>
                        </div>
                    </a>
                </li>
                <li class="tab right-tab">
                    <a href="{{ url_for('courses.index') }}">
                        <div class="row tab-wrap">
                            <img src="{{ url_for('static', filename='img/courses/lessons/icons/list.svg') }}" alt=""> <span class="tab-title">Выбор предметов</span>
                        </div>
                    </a>
                </li>
            </ul>
            <div class="subjects">
                {% block courses %}
                    {% for course in courses %}
                        <a href="{{ url_for('courses.index', id=course.id) }}" class="subj">
                            <img src="{{ icons[course.course_type] }}" alt="" class="subj-icon">
                            <div class="subj-text column">
                                <div class="subj-title">{{ course.name }}</div>
                                <div class="subj-descryption">
                                    {{ course.description }}
                                </div>
                            </div>
                        </a>
                    {% endfor %}
                {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script src="{{ url_for('static', filename='js/courses/lessons.js') }}"></script>
{% endblock %}

app/templates/courses/base.html
<!DOCTYPE html>
<html lang="en">
{% block head %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block styles %}
    {% endblock %}
</head>
{% endblock %}
<body>
    {% block nav %}
        <header>
            <div class="header">
                <div class="container">
                    <div class="header_body">
                        <div class="header_burger">
                            <span></span>
                        </div>
                        <nav class="header_menu">
                            <ul class="header_list">
                                <li><a href="{{ url_for('main.index') }}" class="header_link {{ 'active_link' if
                                active_page=='index' else ''}}
                                }}">Главная</a></li>
                                <li><a href="{{ url_for('courses.user_courses') }}" class="header_link {{ 'active_link' if
                                active_page=='courses' or active_page=='active_courses' else ''}}">Список
                                    предметов</a></li>
                                <li><a href="{{ url_for('projects.index') }}" class="header_link {{ 'active_link' if
                                active_page=='projects' else ''}}">Запись на
                                    проект</a></li>
{#                                {% if current_user.role == "Администратор" %}#}
{#                                    <li><a href="{{ url_for('course.index_view') }}" class="header_link">Админ панель</a></li>#}
{#                                {% endif %}#}
                                {% if current_user.is_authenticated %}
                                    <li><a href="{{ url_for('auth.logout') }}" class="header_link">Выйти</a></li>
                                {% else %}
                                    <li><a href="{{ url_for('auth.oidc') }}" class="header_link">Войти</a></li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
    {% endblock %}
	{% block content %}
    {% endblock %}
    {% block footer %}
        <footer class="foot">
            <div class="footer_container">
                <h1 class="footer_title">Карта сайта</h1>
                <div class="footer_items">
                    <a href="{{ url_for('main.index') }}" class="footer_nav">главная</a>
                    <a href="{{ url_for('courses.user_courses') }}" class="footer_nav">список предметов</a>
                    <a href="{{ url_for('projects.index') }}" class="footer_nav">запись на проект </a>
                    {% if current_user.is_authenticated %}
                        <a href="{{ url_for('auth.logout') }}" class="footer_nav">выход</a>
                    {% endif %}
                </div>
            </div>

            <div class="footer_container">
                <h1 class="footer_title">Контакты</h1>
                <div class="footer_items">
                    <a href="https://vk.com/proictis" class="footer_nav">vk</a>

                </div>
            </div>
        </footer>
    {% endblock %}
    {% block scripts %}
    {% endblock %}
</body>

</html>

app/templates/courses/course_page.html
{% extends 'courses/base.html' %}
{% block title %}
{{ course.name }}
{% endblock %}
{% block styles %}
{#    <link rel="stylesheet" href="{{ url_for('static', filename='css/courses/menu.css') }}">#}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/courses/normalize.css') }}">
{#    <link rel="stylesheet" href="{{ url_for('static', filename='fonts/fonts.css') }}">#}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/courses/LessonPage.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/courses/footer.css') }}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&display=swap" rel="stylesheet">

{% endblock %}
{% block content %}
    </header>
    <div class="header_main">
        <div class="head_description">
            <div class="psevdTop">
            </div>
            <!--Название курса-->
            <h1>
                {{course.name}}
            </h1>
            {% if course.students  %}
                {% if (current_user.id not in course.students) and current_user.role ==
                        "Студент"  %}
                    <div class="psevdBot">
                        <!--Статус записи-->
                        <div class="status btn_to_write">
                            <a>Записаться</a>
                        </div>
                    </div>
                {% endif %}
            {% elif current_user.role =="Студент" %}
                <div class="psevdBot">
                        <!--Статус записи-->
                        <div class="status btn_to_write">
                            <a>Записаться</a>
                        </div>
                </div>
            {% endif %}
        </div>
    </div>
    <div class="AboutCourse">
        <div class="LeftSide">
            <div class="CourseDescription">
                <h2 class="CourseTitle">Опиcание курса</h2>
                <!--Опсиние курса-->
                <p class="CourseP">
                    {{ course.description }}
                </p>

                <div class="Where">
                    <div class="infoGroup">
                        <span class="WhereElem">
                            Лекции:
                        </span>
                        <!--Если аудиторно, то ссылка пуста,
                            Текст - номер аудтории.
                        Если онлайн, то ссылка на тимс, текст "Teams"-->
                        {% for temp in course.lectures_auds %}
                            {% if 'teams.microsoft.com' in temp.name  %}
                                <a class="WhereElem aud_link" href="{{ temp.name }}">
                                    Teams
                                </a>
                            {% else %}
                                <a class="WhereElem aud_link" href="#">
                                    {{ temp.name }}
                                </a>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="CourseTeachers">
                    <h2 class="CourseTitle">
                        Преподаватели
                    </h2>
                    {% block teachers %}
                        {% for teacher in course.teachers  %}
                            <div class="teacher">
                                <div class="teacherTitle">
                                    <!--Имя препода -->
                                    <h3 class="H3teacher">{{ teacher.fullname }}</h3>
                                </div>
                                <!--Должность препода -->
                                <p class="CourseP">
                                    {{ teacher.description }}
                                </p>
                                <div class="contact">
                                    <!-- Почта препода-->
                                    <div class="eMail">
                                        {{ teacher.email }}
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% endblock %}
            </div>
            <div class="crossing">
                <!-- Текст пересечения-->
                {% if course.links %}
                    <h2 class="CourseTitle">
                        Пересечения
                    </h2>
                    <p class="CourseP">
                        Знания, полученные в ходе прохождения этого
                        курса, могут пригодится
                        в следующих: {{', '.join(course.links | map(attribute='name') | list)}}.
                    </p>
                {% endif %}
            </div>
        </div>
        <div class="RightSide">
            {% block themes %}
                {% for theme in course.themes %}
                    <div class="ThemeContainer">
                        <div class="SideBar">
                            <svg class="arrow" width="19" height="11" viewBox="0 0 19 11" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M17 9L10.1823 2.63683C9.79811 2.27824 9.20189 2.27824 8.81768 2.63683L2 9" stroke="black" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>
                            </svg>
                            <span class="TextOnLeft">
                               Описание
                            </span>
                        </div>
                        <div class="Theme">
                            <!--Название темы предмета-->
                            <h2>
                                {{ theme.name }}
                            </h2>
                            <div class="HiddenInfo">
                                <!--Описание темы предмета-->
                                <p class="themePar">
                                    {{ theme.description | safe}}
                                </p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endblock %}
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{{ url_for('static', filename='js/courses/LessonPage.js') }}"></script>
    <script src="{{ url_for('static', filename='js/courses/lessons.js') }}"></script>
    <script src="{{ url_for('static', filename='js/courses/button_handler.js') }}"></script>
{% endblock %}

app/templates/courses/courses.html
{% extends 'courses/base.html' %}
{% set active_page = "courses" %}
{% block title %}
Курсы
{% endblock %}
{% block styles %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/courses/lessons.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/courses/footer.css') }}">
{% endblock %}
{% block content %}
       <div class="header-text row">
            <div class="column">
                <h1 class="title">СПИСОК ПРЕДМЕТОВ</h1>
                <div class="descryption">
                    Здравствуй, <span class = "active-link">{{ current_user.fullname }}</span>! На этой странице ты
                    можешь просмотреть информацию по интересующим тебя
                    предметам. Она должна помочь в подготовке к экзамену, контрольной или просто штудировании!
                </div>
            </div>
        </div>
    </header>
    <div class="main row">
        <div class="main-wrap column">
            <ul class="tabs row">
                <li class="tab left-tab">
                    <a href="{{ url_for('courses.user_courses') }}">
                        <div class="row tab-wrap">
                            <img src="{{ url_for('static', filename='img/courses/lessons/icons/check-list.svg') }}" alt=""> <span class="tab-title">Выбранные
                                предметы</span>
                        </div>
                    </a>
                </li>
                <li class="tab right-tab active-tab">
                    <a href="{{ url_for('courses.index') }}">
                        <div class="row tab-wrap">
                            <img src="{{ url_for('static', filename='img/courses/lessons/icons/list.svg') }}" alt=""> <span class="tab-title">Выбор предметов</span>
                        </div>
                    </a>
                </li>
            </ul>
            <div class="subjects">
                {% block courses %}
                    {% for course in courses %}
                        <a href="{{ url_for('courses.index', id=course.id) }}" class="subj">
                            <img src="{{ icons[course.course_type] }}" alt="" class="subj-icon">
                            <div class="subj-text column">
                                <div class="subj-title">{{ course.name }}</div>
                                <div class="subj-descryption">
                                    {{ course.description }}
                                </div>
                            </div>
                        </a>
                    {% endfor %}
                {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script src="{{ url_for('static', filename='js/courses/lessons.js') }}"></script>
{% endblock %}